- hosts: leaf2
  name: TS-02
  become: yes
  gather_facts: no
  tasks:
    - name: TS-02
      copy: 
        src: /home/cumulus/ON-12/TS-02
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate 
      shell: /sbin/ifreload -a
