# TS-00 fuer die Veranstaltung in der ersten April Woche...

# Host e/n/i Datei

- hosts: host leaf spine
  name: host Interfaces
  become: yes
  gather_facts: no
  tasks:
    - name: IPv4 Address
      copy: 
        src: /home/cumulus/ON-12/practice-05-{{ inventory_hostname }}-if
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate changes on hosts
      shell: /sbin/ifreload -a

# #################################################################
# #################################################################
# #################################################################   
      
- hosts: leaf spine
  name: Routing 
  become: yes
  gather_facts: no
  tasks:
    - name: dies und das
      copy:
        src: /home/cumulus/ON-12/practice-05-{{ inventory_hostname }}-frr
        dest: /etc/frr/frr.conf
      notify:
        - frr_reload
        
  handlers:
    - name: frr_reload
      service:
        name=frr
        state=reloaded
      listen: "frr_reload"
      
# #################################################################
