- hosts: host2
  name: TS-05
  become: yes
  gather_facts: no
  tasks:
    - name: TS-05
      shell: arp -s 172.16.19.1 44:39:39:00:00:14
      
- hosts: leaf1
  name: TS-05
  become: yes
  gather_facts: no
  tasks:
    - name: TS-05
      shell: ip neigh change 169.254.0.1 lladdr 44:38:38:00:00:05 dev swp1 nud permanen
      shell: ip neigh change 169.254.0.1 lladdr 44:38:38:00:00:0b dev swp2 nud permanen
      shell: ip neigh change fe80::4638:39ff:fe00:5 lladdr 44:38:38:00:00:05 dev swp1 nud permanent
      shell: ip neigh change fe80::4638:39ff:fe00:b lladdr 44:38:38:00:00:0b dev swp2 nud permanent




# 44:38:39:00:00:05
