- hosts: spine3
  name: TS-06
  become: yes
  gather_facts: no
  no_log: True
  tasks:
    - name: TS-06
      copy: 
        src: /home/cumulus/ON-12/TS-06
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate 
      shell: /sbin/ifreload -a
