- hosts: spine
  name: TS-03
  become: yes
  gather_facts: no
  tasks:
    - name: TS-03
      copy: 
        src: /home/cumulus/ON-12/TS-03
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate 
      shell: /sbin/ifreload -a
      
    # aktivieren
    - name: activate 
      shell: systemctl restart frr
