- hosts: host2
  name: TS-05
  become: yes
  gather_facts: no
  tasks:
    - name: TS-05
      shell: arp -d 172.16.19.1 
      # 172.16.19.1 dev eth2 lladdr 44:38:39:00:00:14 REACHABLE

      
- hosts: leaf1
  name: TS-05
  become: yes
  gather_facts: no
  tasks:
    - name: TS-05
      shell: ip neigh change 169.254.0.1 lladdr 44:38:39:00:00:05 dev swp1 nud permanen
      shell: ip neigh change 169.254.0.1 lladdr 44:38:39:00:00:0b dev swp2 nud permanen
      shell: ip neigh change fe80::4638:39ff:fe00:5 lladdr 44:38:39:00:00:05 dev swp1 nud permanent
      shell: ip neigh change fe80::4638:39ff:fe00:b lladdr 44:38:39:00:00:0b dev swp2 nud permanent
