- hosts: leaf1
  name: TS-01
  become: yes
  gather_facts: no
  tasks:
    - name: TS-01
      copy: 
        src: /home/cumulus/ON-12/TS-01
        dest: /etc/network/interfaces
    # aktivieren
    - name: activate 
      shell: /sbin/ifreload -a
