- hosts: leaf1
  name: copy ztp
  become: yes
  gather_facts: no
  tasks:
    - name: prepare
      file:
        state: absent
        path: /var/lib/cumulus/ztp/test.txt

    - name: ZTP troubleshooting
      copy:
        src: /home/cumulus/ON-12/ztp.sh
        dest: /var/lib/cumulus/ztp/cumulus-ztp
        mode: '0644'
        owner: 'root'
        group: 'root'

    - name: run ZTP manually
      shell: ztp --run /var/lib/cumulus/ztp/cumulus-ztp
      
    - name: verify ZTP
      shell: ztp -s
      register: ztps
      
    - name: print msg
      debug: msg={{ ztps }}
      
